/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  auth: [{type: 'autogenerated', dirName: 'auth'}],

  // But you can create a sidebar manually
  
  user: [
    'user/user',
    'user/id'
  ],
  org: [
    'org/org',
    'org/id',
    'org/budget',
    'org/budgetid',
    'org/receipt',
    'org/receiptid',
    'org/purchase',
    'org/purchaseid',
    'org/goal',
    'org/goalid'
  ]
   
};

export default sidebars;
